services:
  - type: web
    name: mock-interview-app
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: mock-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: mock-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: mock-db
          property: password

databases:
  - name: mock-db
    databaseName: mockdb
    user: mockuser
    plan: free
